makeswift/vibes

apps/web/vibes/soul/components/checkbox/index.tsx
apps/web/vibes/soul/components/dropdown/index.tsx
apps/web/vibes/soul/components/inline-email-form/index.tsx
apps/web/vibes/soul/components/input/index.tsx
apps/web/vibes/soul/components/product-card/compare.tsx
apps/web/vibes/soul/components/slideshow/index.tsx
apps/web/vibes/soul/examples/checkbox.tsx
apps/web/vibes/soul/examples/dropdown.tsx
apps/web/vibes/soul/examples/input.tsx

- start adding error states to form inputs (so far, only input, select, & checkbox)
- fix slideshow controls positioning
- move subscribe aria-label to submit button

soul: add error states to form components

---

apps/web/components/ui/installation.tsx

docs: hide cli option for installation

---

apps/web/package.json
apps/web/vibes/soul/docs/calendar.mdx
apps/web/vibes/soul/examples.ts
apps/web/vibes/soul/examples/primitives/calendar/electric.tsx
apps/web/vibes/soul/examples/primitives/calendar/luxury.tsx
apps/web/vibes/soul/examples/primitives/calendar/warm.tsx
apps/web/vibes/soul/navigation.ts
apps/web/vibes/soul/primitives.ts
apps/web/vibes/soul/primitives/calendar.tsx
pnpm-lock.yaml

Adds a `calendar` primitive that will be used for the `DatePicker` form component.

feat: adds Calendar primitive

---

apps/web/app/(marketing)/docs/[vibe]/[page]/page.tsx
apps/web/app/(marketing)/docs/[vibe]/page.tsx
apps/web/app/(preview)/preview/[vibe]/[component]/[brand]/page.tsx
apps/web/app/(preview)/preview/[vibe]/[component]/page.tsx

This reverts commit 048a35f49c31301b0c97a30e2bd00892abc5f431.

Revert "feat: use ISR to reduce build times"

---

apps/web/vibes/soul/form/number-input/index.tsx
apps/web/vibes/soul/primitives/navigation/index.tsx

fix: hydration errors

---

apps/web/vibes/soul/examples/primitives/accordions/index.tsx
apps/web/vibes/soul/examples/sections/reviews/index.tsx
apps/web/vibes/soul/primitives/card-carousel/index.tsx
apps/web/vibes/soul/primitives/cursor-pagination/index.tsx
apps/web/vibes/soul/primitives/navigation/index.tsx
apps/web/vibes/soul/primitives/products-carousel/index.tsx
apps/web/vibes/soul/sections/reviews/index.tsx

- Add empty state and skeletons for all 3
- Automatically fallback to empty state when arrays are empty
- Add `scroll` to `CursorPagination` to disable scrolling for `Reviews`

Update Reviews, ProductsCarousel, CardCarousel

---

apps/web/vibes/soul/sections/featured-products-list/index.tsx

`<ProductList />` accepts a Promise so this change just exposes that to`<FeaturedProductList />` component to allow streaming.

fix: add missing streamable products prop in featured product list

---

apps/web/vibes/soul/sections/subscribe/index.tsx

- Missing placeholder prop for localization purposes.
- Made description optional.

fix: add placeholder prop to Subscribe

---

apps/web/vibes/soul/primitives/inline-email-form/index.tsx

Fixes the issue of having no space in between input and error.

fix: ENG-6917 add space between input and error in Subscribe

---

apps/web/vibes/soul/examples/sections/featured-products-carousel/index.tsx
apps/web/vibes/soul/primitives/products-carousel/index.tsx
apps/web/vibes/soul/sections/featured-products-carousel/index.tsx

Exports a Skeleton.
Still missing empty state.

feat: ENG-6931 export FeaturedProductsCarouselSkeleton

---

apps/web/vibes/soul/examples/sections/featured-products-list/electric.tsx
apps/web/vibes/soul/examples/sections/featured-products-list/luxury.tsx
apps/web/vibes/soul/examples/sections/featured-products-list/warm.tsx
apps/web/vibes/soul/sections/featured-products-list/index.tsx

Export Skeleton and add to examples.

feat: VIB-950 export FeaturedProductListSkeleton

---

apps/web/vibes/soul/examples/sections/header-section/electric.tsx
apps/web/vibes/soul/examples/sections/header-section/luxury.tsx
apps/web/vibes/soul/examples/sections/header-section/warm.tsx
apps/web/vibes/soul/primitives/navigation/index.tsx

+ Add streaming to the Header props:
+ logo
+ cartCount
+ links
+ Fix image props
+ Add missing aria label props
I don't think we need to stream in locales because this should be hardcoded afaik.
Update examples to showcase this behavior.
https://github.com/user-attachments/assets/67b22667-75c8-45ea-b890-626ab51478c5

feat: add streamable props to Header

---

apps/web/vibes/soul/examples/sections/footer/electric.tsx
apps/web/vibes/soul/examples/sections/footer/luxury.tsx
apps/web/vibes/soul/examples/sections/footer/warm.tsx
apps/web/vibes/soul/sections/footer/index.tsx

- Add streamable props to the Soul footer section
- Add skeletons for streamable props
- Add examples for vibes that simulate props as promises
https://github.com/user-attachments/assets/3d9a7039-1446-48ba-abde-e92294e046b5

feat: add streamable props to Soul footer

---

apps/web/vibes/soul/docs/banner.mdx
apps/web/vibes/soul/examples/pages/blog/index.tsx
apps/web/vibes/soul/examples/pages/blog/post/electric.tsx
apps/web/vibes/soul/examples/pages/blog/post/luxury.tsx
apps/web/vibes/soul/examples/pages/blog/post/warm.tsx
apps/web/vibes/soul/examples/pages/cart/electric.tsx
apps/web/vibes/soul/examples/pages/cart/luxury.tsx
apps/web/vibes/soul/examples/pages/cart/warm.tsx
apps/web/vibes/soul/examples/pages/home/electric.tsx
apps/web/vibes/soul/examples/pages/home/luxury.tsx
apps/web/vibes/soul/examples/pages/home/warm.tsx
apps/web/vibes/soul/examples/pages/not-found/electric.tsx
apps/web/vibes/soul/examples/pages/not-found/luxury.tsx
apps/web/vibes/soul/examples/pages/not-found/warm.tsx
apps/web/vibes/soul/examples/pages/product/electric.tsx
apps/web/vibes/soul/examples/pages/product/luxury.tsx
apps/web/vibes/soul/examples/pages/product/warm.tsx
apps/web/vibes/soul/examples/pages/products/electric.tsx
apps/web/vibes/soul/examples/pages/products/luxury.tsx
apps/web/vibes/soul/examples/pages/products/warm.tsx
apps/web/vibes/soul/examples/primitives/banner/index.tsx
apps/web/vibes/soul/examples/sections/header-section/electric.tsx
apps/web/vibes/soul/examples/sections/header-section/luxury.tsx
apps/web/vibes/soul/examples/sections/header-section/warm.tsx
apps/web/vibes/soul/primitives/banner/index.tsx
apps/web/vibes/soul/sections/header-section/index.tsx

- Require an id that is used to hide or show banner.
- Update examples.
- Compute the height of the banner instead of using state.

fix: require id for banner component

---

apps/web/vibes/soul/primitives/product-card/index.tsx

Adds discernible label to Link for accessibility purposes.

fix: add aria-label to ProductCard link

---

apps/web/vibes/soul/primitives/blog-post-carousel/index.tsx
apps/web/vibes/soul/primitives/card-carousel/index.tsx
apps/web/vibes/soul/primitives/carousel/index.tsx
apps/web/vibes/soul/sections/featured-blog-post-carousel/index.tsx
apps/web/vibes/soul/sections/featured-card-carousel/index.tsx

- Adds missing [slider role props](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/slider_role)
- Exposes `carouselScrollbarLabel` prop to components

feat: add accessibility props to carousel scrollbar

---

apps/web/vibes/soul/primitives/navigation/index.tsx

Missing `aria-label` required for accessibility.

feat: add aria-label to toggle navigation button

---

apps/web/vibes/soul/primitives/carousel/index.tsx

Fixes this issue by making sure the scrollbar position is set correctly on `reInit`:
https://github.com/user-attachments/assets/ec646b8c-6c4d-4552-b256-e992ab7f712f

fix: resets scrollbar progress on reInit

---

apps/web/vibes/soul/primitives/blog-post-carousel/index.tsx
apps/web/vibes/soul/primitives/card-carousel/index.tsx
apps/web/vibes/soul/primitives/carousel/index.tsx
apps/web/vibes/soul/primitives/products-carousel/index.tsx
apps/web/vibes/soul/sections/compare-section/index.tsx
apps/web/vibes/soul/sections/featured-blog-post-carousel/index.tsx
apps/web/vibes/soul/sections/featured-products-carousel/index.tsx

We also need labels in the buttons.

fix: missing labels to carousel buttons

---

apps/web/vibes/soul/examples/sections/featured-products-carousel/index.tsx
apps/web/vibes/soul/examples/sections/featured-products-list/electric.tsx
apps/web/vibes/soul/examples/sections/featured-products-list/luxury.tsx
apps/web/vibes/soul/examples/sections/featured-products-list/warm.tsx
apps/web/vibes/soul/primitives/products-carousel/index.tsx
apps/web/vibes/soul/primitives/products-list/index.tsx
apps/web/vibes/soul/sections/featured-products-list/index.tsx
apps/web/vibes/soul/sections/sticky-sidebar-layout/index.tsx

- Add empty state for `ProductList`
- Update examples for `FeaturedProductList`
- Update image mask for `ProductCarousel` and `ProductList` to match Figma designs
https://github.com/user-attachments/assets/f32db019-08ac-468d-955f-17cf9d9bd804

feat: add empty state to ProductsList

---

apps/web/vibes/soul/sections/footer/index.tsx

Add props for accessibility. Remove link when not being used.

fix: add logoHref and logoLabel props to footer

---

apps/web/vibes/soul/examples/sections/product-description/electric.tsx
apps/web/vibes/soul/examples/sections/product-description/luxury.tsx
apps/web/vibes/soul/examples/sections/product-description/warm.tsx
apps/web/vibes/soul/sections/product-description/index.tsx

- Add streamable accordions and image props.
- Suspense and render skeleton.
- Update examples.
https://github.com/user-attachments/assets/dc99cf1c-1c23-4ee3-88f1-76c4981f2ede

feat: add streamable props to ProductDescription

---

apps/web/vibes/soul/examples/sections/product-detail/electric.tsx
apps/web/vibes/soul/examples/sections/product-detail/luxury.tsx
apps/web/vibes/soul/examples/sections/product-detail/warm.tsx
apps/web/vibes/soul/primitives/breadcrumbs/index.tsx
apps/web/vibes/soul/sections/product-detail/index.tsx

+ Adds streamable props
+ Renders skeleton when loading
+ Updates examples
For this, I'm not sure if the best way to go is to add the streamable prop to each of the inner components or the way I implemented this the right solution. I also understand if we want to move the skeletons to the inner components. Let me know. cc @migueloller 
https://github.com/user-attachments/assets/fc57aca2-b948-4590-a59d-c0f1cd1b7ab2

feat: add streamable props to ProductDetail

---

apps/web/vibes/soul/primitives/breadcrumbs/index.tsx
apps/web/vibes/soul/sections/product-detail/index.tsx

- Updates breadcrumb skeleton to match new design
- Adds `className` to breadcrumbs skeleton
https://github.com/user-attachments/assets/a5f4b7ae-ada6-4a6f-a94d-9c0923dc8851

fix: update breadcrumbs to match new design

---

apps/web/app/(preview)/style/globals.css
apps/web/vibes/soul/examples/primitives/accordions/index.tsx
apps/web/vibes/soul/primitives/accordions/index.tsx

Added light and dark Accordion with customizable CSS variables.

feat: add accordion contrast and css variables

---

apps/web/vibes/soul/form/number-input/index.tsx

Only the input field was being disabled, after this change both buttons should be disabled as well.

fix: allow disabling NumberInput component

---

apps/web/vibes/soul/primitives/product-card/index.tsx

- Adds `imagePriority` prop to `ProductCard` for image pre-loading option
Locally

feat: add imagePriority prop to ProductCard

---

apps/web/vibes/soul/examples/primitives/cursor-pagination/index.tsx
apps/web/vibes/soul/primitives/cursor-pagination/index.tsx

The changes here are heavily inspired by shadcn/ui Pagination component.
See https://ui.shadcn.com/docs/components/pagination.
https://github.com/user-attachments/assets/0a9712e4-05a8-4d97-ad93-c3d48922b35d

feat: make CursorPagination component accessible

---

apps/web/vibes/soul/examples/pages/blog/index.tsx
apps/web/vibes/soul/examples/sections/featured-blog-post-list/index.tsx
apps/web/vibes/soul/sections/blog-post-list/index.tsx
apps/web/vibes/soul/sections/featured-blog-post-list/index.tsx

- Add empty state for BlogPostList component and use it in the FeaturedBlogPostList section
- Update examples

feat: add empty state to BlogPostList

---

apps/web/vibes/soul/examples/pages/blog/index.tsx
apps/web/vibes/soul/examples/pages/blog/post/electric.tsx
apps/web/vibes/soul/examples/pages/blog/post/luxury.tsx
apps/web/vibes/soul/examples/pages/blog/post/warm.tsx
apps/web/vibes/soul/examples/primitives/blog-post-card/index.tsx
apps/web/vibes/soul/examples/sections/blog-post-list/index.tsx
apps/web/vibes/soul/examples/sections/featured-blog-post-list/index.tsx
apps/web/vibes/soul/primitives/blog-post-card/index.tsx
apps/web/vibes/soul/primitives/blog-post-carousel/index.tsx
apps/web/vibes/soul/sections/blog-post-content/index.tsx
apps/web/vibes/soul/sections/blog-post-list/index.tsx
apps/web/vibes/soul/sections/featured-blog-post-carousel/index.tsx
apps/web/vibes/soul/sections/featured-blog-post-list/index.tsx

- Create BlogPostContentSkeleton component do display while blog post page is being loaded
- Make the BlogPostContent props streamable in order to display the skeleton before the data is ready

feat: create BlogPostContentSkeleton, make BlogPostContent props streamable

---

apps/web/vibes/soul/primitives/logo/index.tsx
apps/web/vibes/soul/primitives/navigation/index.tsx
apps/web/vibes/soul/sections/footer/index.tsx

This also fixes the Footer issue where image logos are collapsed.

feat: add height prop to Logo

---

apps/web/vibes/soul/primitives/accordions/index.tsx
apps/web/vibes/soul/sections/products-list-section/filters-panel.tsx

When the products list section loaded the accordion has all items collapsed and it would then open once JS loaded. This change guarantees they render as open on initial load.

feat: accordion items default open

---

apps/web/vibes/soul/docs/page-error.mdx
apps/web/vibes/soul/examples.ts
apps/web/vibes/soul/examples/pages/error/index.tsx
apps/web/vibes/soul/navigation.ts
apps/web/vibes/soul/sections/error/index.tsx

Add the `Error` page component and examples

feat: add Error page and section

---

apps/web/vibes/soul/form/select/index.tsx

See
https://www.radix-ui.com/primitives/docs/components/select#api-reference.

fix: pass `name` to Select root instead of trigger

---

.github/workflows/ci.yml
apps/web/package.json
apps/web/tsconfig.json
apps/web/turbo.json
apps/web/vibes/soul/lib/streamable.test.ts
apps/web/vibes/soul/lib/streamable.tsx
apps/web/vibes/soul/primitives/products-list/index.tsx
apps/web/vibes/soul/sections/product-detail/index.tsx
apps/web/vibes/soul/sections/products-list-section/index.tsx
apps/web/vitest.config.mts
package.json
pnpm-lock.yaml

A suspense-friendly upgrade to `Promise.all`, guarantees stability of the returned promise instance if passed an identical set of inputs.

feat: add `Streamable.all`, use it in `ProductDetail`/`ProductList`

---

apps/web/vibes/soul/lib/streamable.tsx
apps/web/vibes/soul/primitives/banner/index.tsx
apps/web/vibes/soul/sections/product-detail/index.tsx

fix: bring over misc minor fixes from Catalyst

---

apps/web/vibes/soul/examples/sections/address-list-section/actions.ts
apps/web/vibes/soul/examples/sections/address-list-section/index.tsx
apps/web/vibes/soul/primitives/dynamic-form/index.tsx
apps/web/vibes/soul/primitives/dynamic-form/schema.ts
apps/web/vibes/soul/sections/address-list-section/index.tsx
apps/web/vibes/soul/sections/address-list-section/schema.ts

Draft PR for migrating the AddressListSection over to using the `DynamicForm`.

feat: migrate address form to use dynamic form

---

apps/web/vibes/soul/docs/page-maintenance.mdx
apps/web/vibes/soul/examples.ts
apps/web/vibes/soul/examples/pages/maintenance/index.tsx
apps/web/vibes/soul/navigation.ts
apps/web/vibes/soul/sections/maintenance/index.tsx

Add Down for Maintenance page to vibes

Add Down for Maintenance page

---

apps/web/vibes/soul/sections/product-detail/index.tsx

feat: add sr-only heading for additional information in PDP

---

apps/web/vibes/soul/data/products.ts
apps/web/vibes/soul/examples/pages/home/electric.tsx
apps/web/vibes/soul/examples/pages/home/luxury.tsx
apps/web/vibes/soul/examples/pages/home/warm.tsx
apps/web/vibes/soul/examples/primitives/card-carousel/electric.tsx
apps/web/vibes/soul/examples/primitives/card-carousel/luxury.tsx
apps/web/vibes/soul/examples/primitives/card-carousel/warm.tsx
apps/web/vibes/soul/examples/primitives/products-carousel/index.tsx
apps/web/vibes/soul/examples/sections/compare-section/electric.tsx
apps/web/vibes/soul/examples/sections/compare-section/luxury.tsx
apps/web/vibes/soul/examples/sections/compare-section/warm.tsx
apps/web/vibes/soul/primitives/card-carousel/index.tsx
apps/web/vibes/soul/primitives/card/index.tsx
apps/web/vibes/soul/primitives/carousel/index.tsx
apps/web/vibes/soul/primitives/compare-card/index.tsx
apps/web/vibes/soul/primitives/product-card/index.tsx
apps/web/vibes/soul/primitives/products-carousel/index.tsx
apps/web/vibes/soul/sections/compare-section/index.tsx
apps/web/vibes/soul/sections/featured-card-carousel/index.tsx

- Remove Embla carousel from skeleton and empty components
- Add streamable pattern to `CardCarousel`
https://github.com/user-attachments/assets/68737111-f905-4fbd-97e7-5d615e58a9b5
https://github.com/user-attachments/assets/6f8d2945-31e5-46c7-a221-ef9e6481c030

fix: remove carousel from skeletons

---

apps/web/vibes/soul/primitives/navigation/index.tsx
apps/web/vibes/soul/sections/header-section/index.tsx

- Fixes an issue with the height of the link skeletons and the resulting links.
- Updated the skeletons to be a little longer depicting more real use cases.
- Fix a linting issues that we get in Catalyst.
https://github.com/user-attachments/assets/f250f89b-923b-421a-afc7-203a7a6ff17f
https://github.com/user-attachments/assets/7cdad347-9d1f-4997-992c-9823861a1742

fix: issue with skeleton height in Header

---

apps/web/vibes/soul/sections/cart/client.tsx

Want to make sure we follow the pattern from other components.

feat: show toast instead of console.error in Cart checkout button

---

apps/web/vibes/soul/form/button-radio-group/index.tsx
apps/web/vibes/soul/form/card-radio-group/index.tsx
apps/web/vibes/soul/form/checkbox-group/index.tsx
apps/web/vibes/soul/form/date-picker/index.tsx
apps/web/vibes/soul/form/field-error/index.tsx
apps/web/vibes/soul/form/form-status/index.tsx
apps/web/vibes/soul/form/input/index.tsx
apps/web/vibes/soul/form/label/index.tsx
apps/web/vibes/soul/form/number-input/index.tsx
apps/web/vibes/soul/form/radio-group/index.tsx
apps/web/vibes/soul/form/range-input/index.tsx
apps/web/vibes/soul/form/select/index.tsx
apps/web/vibes/soul/form/swatch-radio-group/index.tsx
apps/web/vibes/soul/form/textarea/index.tsx
apps/web/vibes/soul/form/toggle-group/index.tsx
apps/web/vibes/soul/primitives/calendar.tsx

- Adds new CSS variables to support custom theming for forms
https://github.com/user-attachments/assets/cd85bdaf-d2ab-49a8-9266-d989c6ed6caf

feat: add CSS theme variables for form components

---

apps/web/vibes/soul/primitives/accordions/index.tsx

- Fixes padding and font-family
- Adds focus-visible style to accordion
- Exports interface
https://github.com/user-attachments/assets/87d64fa2-3389-4e42-879a-bcd3820bbdd2

audit: Accordion primitive

---

apps/web/vibes/soul/examples/primitives/animated-link/index.tsx
apps/web/vibes/soul/primitives/animated-link/index.tsx
apps/web/vibes/soul/primitives/breadcrumbs/index.tsx
apps/web/vibes/soul/sections/featured-blog-post-carousel/index.tsx
apps/web/vibes/soul/sections/featured-card-carousel/index.tsx
apps/web/vibes/soul/sections/featured-products-carousel/index.tsx

- Refactors `AnimatedLink` to behave like Next's `Link` component since it's just a styled version
- Adds CSS variables
- Fixes examples using old `AnimatedLink`
- Exports interface props
https://github.com/user-attachments/assets/047baedd-11ed-4c54-9031-453216dbd761

audit: animated link

---

apps/web/vibes/soul/sections/reviews/index.tsx

See https://github.com/bigcommerce/catalyst/pull/1971#pullrequestreview-2609984967 for more context.

fix: handle pagination labels in Reviews section

---

apps/web/vibes/soul/docs/accordion.mdx

- **docs: wip accordion docs**
- **docs: update accordion docs**

Accordion Docs

---

apps/web/vibes/soul/primitives/button/index.tsx
apps/web/vibes/soul/primitives/dynamic-form/index.tsx

- Exports `ButtonProps` interface
- Updates CSS variables to match the current naming pattern
- Inherits props from native `button` element and passes them down with `...props`
https://github.com/user-attachments/assets/4595af8e-5b9b-49fe-83af-6e5f753cc85a

audit: button component

---

apps/web/vibes/soul/primitives/button-link/index.tsx

- Exports `ButtonLinkProps` interface
- Renames variables with the current naming pattern
https://github.com/user-attachments/assets/9083f99f-06b3-4ae7-afbd-2fb8fcfdb560

Audit button link

---

apps/web/vibes/soul/docs/accordion.mdx
apps/web/vibes/soul/docs/alert.mdx
apps/web/vibes/soul/docs/animated-link.mdx
apps/web/vibes/soul/primitives.ts

- remove figma link
- update API reference to link to Next.js docs
- update dependency for `clsx`
- update usage to current API
- codeblocks to have a language of "ts"
- update usage snippets for alert and accordion

AnimatedLink Docs

---

apps/web/vibes/soul/docs/accordion.mdx
apps/web/vibes/soul/docs/badge.mdx

- update Figma link for Badge and Accordion
- update usage example
- update api reference
- add css variables

Badge Docs

---

apps/web/vibes/soul/primitives/carousel/index.tsx

- Imports all React types and hooks as named 
- Exports props interface
- Changes `...rest` to `...props`

audit: carousel

---

apps/web/vibes/soul/docs/blog-post-card.mdx
apps/web/vibes/soul/examples.ts
apps/web/vibes/soul/examples/primitives/blog-post-card/electric.tsx
apps/web/vibes/soul/examples/primitives/blog-post-card/luxury.tsx
apps/web/vibes/soul/examples/primitives/blog-post-card/warm.tsx
apps/web/vibes/soul/primitives.ts

- added style examples with different images
- updated API reference
- added skeleton dependency

`Blog-Post-Card` Docs

---

apps/web/vibes/soul/docs/button.mdx

- figma link
- usage
- api reference including css variables
- size of example to show there is content to scroll to

Button Docs

---

apps/web/vibes/soul/primitives/product-card/index.tsx

Add container query to font size on ProductCard

feat: add 'condensed' variant to ProductCard

---

apps/web/vibes/soul/docs/card-carousel.mdx
apps/web/vibes/soul/examples/sections/card-carousel/electric.tsx
apps/web/vibes/soul/examples/sections/card-carousel/luxury.tsx
apps/web/vibes/soul/examples/sections/card-carousel/warm.tsx

- inline data and don't use data directory
- API reference
- Figma link
- usage section

`CardCarousel` Docs

---

apps/web/vibes/soul/examples/primitives/carousel/electric.tsx
apps/web/vibes/soul/examples/primitives/carousel/luxury.tsx
apps/web/vibes/soul/examples/primitives/carousel/warm.tsx

Share updates to James' PR [docs: carousel docs](37e933ccd85aab349b6c50811c72b0b801a088f8)

Hunter carousel docs

---

apps/web/vibes/soul/data/products.ts
apps/web/vibes/soul/docs/compare-card.mdx
apps/web/vibes/soul/examples.ts
apps/web/vibes/soul/examples/pages/home/electric.tsx
apps/web/vibes/soul/examples/pages/not-found/electric.tsx
apps/web/vibes/soul/examples/pages/not-found/luxury.tsx
apps/web/vibes/soul/examples/pages/not-found/warm.tsx
apps/web/vibes/soul/examples/primitives/compare-card/electric.tsx
apps/web/vibes/soul/examples/primitives/compare-card/luxury.tsx
apps/web/vibes/soul/examples/primitives/compare-card/warm.tsx
apps/web/vibes/soul/navigation.ts
apps/web/vibes/soul/primitives.ts
apps/web/vibes/soul/primitives/compare-card/index.tsx
apps/web/vibes/soul/primitives/product-card/index.tsx
apps/web/vibes/soul/primitives/products-carousel/index.tsx
apps/web/vibes/soul/primitives/products-list/index.tsx
apps/web/vibes/soul/sections/compare-section/index.tsx

- Add placeholder docs for `CompareCard`
- Add examples for `CompareCard`
- Add and export interfaces
- Add CSS variables
- Add `CompareCardSkeleton`

audit: compare card

---

apps/web/vibes/soul/examples/sections/countdown/index.tsx
apps/web/vibes/soul/navigation.ts
apps/web/vibes/soul/sections/countdown/index.tsx

- Move Countdown to Sections in the navigation
- Export `CountdownProps` interface
- Add `twoWeeksFromNow` in the example to ensure there's always a working date
- Add CSS vars

audit: countdown

---

apps/web/vibes/soul/docs/accordion.mdx
apps/web/vibes/soul/docs/alert.mdx
apps/web/vibes/soul/docs/animated-link.mdx
apps/web/vibes/soul/docs/badge.mdx
apps/web/vibes/soul/docs/blog-post-card.mdx
apps/web/vibes/soul/docs/blog-post-carousel.mdx
apps/web/vibes/soul/docs/breadcrumbs.mdx
apps/web/vibes/soul/docs/button-link.mdx
apps/web/vibes/soul/docs/button.mdx
apps/web/vibes/soul/docs/calendar.mdx
apps/web/vibes/soul/docs/card-carousel.mdx
apps/web/vibes/soul/docs/card.mdx
apps/web/vibes/soul/docs/carousel.mdx
apps/web/vibes/soul/docs/checkbox.mdx
apps/web/vibes/soul/docs/example.mdx
apps/web/vibes/soul/docs/field-error.mdx
apps/web/vibes/soul/examples.ts
apps/web/vibes/soul/examples/form/field-error/index.tsx
apps/web/vibes/soul/examples/sections/products-list-section/warm.tsx
apps/web/vibes/soul/navigation.ts
apps/web/vibes/soul/primitives.ts

- added FieldError as primitive including docs and example and included in nav
- include `FieldError` as dependency of `Checkbox`
- added Checkbox usage, API reference, and example

`Checkbox` and `FieldError` Docs

---

apps/web/vibes/soul/docs/compare-card.mdx
apps/web/vibes/soul/examples/primitives/compare-card/warm.tsx

- example
- api 
- usage
- figma link

`CompareCard` Docs

---

.github/workflows/ci.yml
apps/web/.eslintrc.json
apps/web/components/ui/table-of-contents.tsx
apps/web/vibes/soul/examples/sections/products-list-section/electric.tsx
apps/web/vibes/soul/examples/sections/products-list-section/luxury.tsx
apps/web/vibes/soul/examples/sections/products-list-section/warm.tsx
package.json
pnpm-lock.yaml
pnpm-workspace.yaml

- Upgrade pnpm to latest version
- Removes conflicting ESLint preset (`plugin:import/recommended`)
- Addresses failing ESLint rules

feat: upgrade pnpm

---

apps/web/vibes/soul/docs/rating.mdx
apps/web/vibes/soul/primitives.ts
apps/web/vibes/soul/primitives/rating/index.tsx

- Exports prop interface
- Adds CSS vars

audit: rating

---

apps/web/vibes/soul/docs/price-label.mdx
apps/web/vibes/soul/examples.ts
apps/web/vibes/soul/examples/primitives/price-label/index.tsx
apps/web/vibes/soul/navigation.ts
apps/web/vibes/soul/primitives/price-label/index.tsx

- Adds doc placeholder for `PriceLabel`
- Adds `PriceLabel` examples
- Exports props interface

audit: price label

---

apps/web/vibes/soul/docs/offset-pagination.mdx
apps/web/vibes/soul/navigation.ts
apps/web/vibes/soul/primitives.ts
apps/web/vibes/soul/primitives/offset-pagination/index.tsx

- adds `OffsetPagination` example
- exports prop interface
- adds CSS variables

audit: offset-pagination

---

apps/web/vibes/soul/docs/icon.mdx
apps/web/vibes/soul/examples.ts
apps/web/vibes/soul/examples/primitives/icon/index.tsx
apps/web/vibes/soul/navigation.ts
apps/web/vibes/soul/primitives.ts
apps/web/vibes/soul/primitives/icon/index.tsx

- Updates `Icon` example
- Updates `IconSkeleton` to use `Skeleton` component

audit: icon

---

apps/web/vibes/soul/docs/logo.mdx
apps/web/vibes/soul/examples.ts
apps/web/vibes/soul/examples/primitives/logo/index.tsx
apps/web/vibes/soul/navigation.ts
apps/web/vibes/soul/primitives.ts
apps/web/vibes/soul/primitives/logo/index.tsx
apps/web/vibes/soul/primitives/navigation/index.tsx
apps/web/vibes/soul/sections/footer/index.tsx
apps/web/vibes/soul/sections/maintenance/index.tsx

- Remove `logo` from being an optional prop
- Export props interface
- Add logo example placeholder files

Audit logo

---

apps/web/vibes/soul/docs/spinner.mdx
apps/web/vibes/soul/examples/primitives/spinner/index.tsx
apps/web/vibes/soul/primitives/spinner/index.tsx

- exports prop interface
- sets default value for `loadingAriaLabel`

audit: spinner

---

apps/web/vibes/soul/docs/toaster.mdx
apps/web/vibes/soul/examples/primitives/toaster/index.tsx
apps/web/vibes/soul/primitives/toaster/index.tsx

- Adds padding to example
- Exports type ( would not let me extend interface of Sonner types)

audit: toaster

---

apps/web/vibes/soul/docs/counter.mdx
apps/web/vibes/soul/primitives.ts
apps/web/vibes/soul/primitives/counter/index.tsx

- exports interface
- add CSS vars

audit: counter

---

apps/web/vibes/soul/docs/address-list-section.mdx
apps/web/vibes/soul/examples.ts
apps/web/vibes/soul/examples/sections/address-list-section/index.tsx
apps/web/vibes/soul/navigation.ts
apps/web/vibes/soul/sections.ts
apps/web/vibes/soul/sections/address-list-section/index.tsx

-  Adds CSS vars
- Exports prop interface
- Uses correct text colors

Audit address list

---

apps/web/vibes/soul/docs/blog-post-list.mdx
apps/web/vibes/soul/examples.ts
apps/web/vibes/soul/examples/pages/blog/index.tsx
apps/web/vibes/soul/examples/pages/blog/post/electric.tsx
apps/web/vibes/soul/examples/pages/blog/post/luxury.tsx
apps/web/vibes/soul/examples/pages/blog/post/warm.tsx
apps/web/vibes/soul/examples/sections/blog-post-list/electric.tsx
apps/web/vibes/soul/examples/sections/blog-post-list/luxury.tsx
apps/web/vibes/soul/examples/sections/blog-post-list/warm.tsx
apps/web/vibes/soul/examples/sections/featured-blog-post-list/index.tsx
apps/web/vibes/soul/navigation.ts
apps/web/vibes/soul/sections.ts
apps/web/vibes/soul/sections/blog-post-list/index.tsx
apps/web/vibes/soul/sections/featured-blog-post-list/index.tsx

- Updates streamable props
- Adds CSS vars
- Updates default props
- Moves to sections in navigation

audit: blog post list

---

apps/web/package.json
apps/web/vibes/soul/docs/blog-post-content.mdx
apps/web/vibes/soul/examples.ts
apps/web/vibes/soul/examples/pages/blog/post/electric.tsx
apps/web/vibes/soul/examples/pages/blog/post/luxury.tsx
apps/web/vibes/soul/examples/pages/blog/post/warm.tsx
apps/web/vibes/soul/examples/sections/blog-post-content/index.tsx
apps/web/vibes/soul/navigation.ts
apps/web/vibes/soul/sections.ts
apps/web/vibes/soul/sections/blog-post-content/index.tsx
apps/web/vibes/tailwind.config.ts
pnpm-lock.yaml

- Installs `@tailwindcss/typography` to support the Tailwind `prose` class
- Adds default styles for elements inside `prose`
- Adds placeholder for `BlogPostContent` in docs
- Exports prop interface
- Refactors skeletons to use `Skeleton` component
- Adds CSS vars

Audit blog post content

---

apps/web/vibes/soul/docs/blog-post-carousel.mdx
apps/web/vibes/soul/docs/featured-blog-post-carousel.mdx
apps/web/vibes/soul/examples/sections/featured-blog-post-carousel/luxury.tsx
apps/web/vibes/soul/examples/sections/featured-blog-post-carousel/warm.tsx
apps/web/vibes/soul/sections.ts
apps/web/vibes/soul/sections/featured-blog-post-carousel/index.tsx

- exports interface props
- adds animation group boundary

audit: featured-blog-post-carousel

---

apps/web/vibes/soul/docs/section-layout.mdx
apps/web/vibes/soul/examples.ts
apps/web/vibes/soul/examples/sections/section-layout/electric.tsx
apps/web/vibes/soul/examples/sections/section-layout/luxury.tsx
apps/web/vibes/soul/examples/sections/section-layout/warm.tsx
apps/web/vibes/soul/navigation.ts
apps/web/vibes/soul/sections.ts
apps/web/vibes/soul/sections/section-layout/index.tsx
plop-templates/register-example.ts.hbs

audit: section layout

---

apps/web/vibes/soul/docs/featured-card-carousel.mdx
apps/web/vibes/soul/examples.ts
apps/web/vibes/soul/examples/sections/featured-card-carousel/electric.tsx
apps/web/vibes/soul/examples/sections/featured-card-carousel/luxury.tsx
apps/web/vibes/soul/examples/sections/featured-card-carousel/warm.tsx
apps/web/vibes/soul/navigation.ts
apps/web/vibes/soul/sections.ts
apps/web/vibes/soul/sections/featured-card-carousel/index.tsx

- adds `FeaturedCardCarousel` example placeholder
- adds section layout

Audit featured card carousel

---

apps/web/vibes/soul/docs/navigation.mdx
apps/web/vibes/soul/docs/toaster.mdx
apps/web/vibes/soul/examples.ts
apps/web/vibes/soul/navigation.ts
apps/web/vibes/soul/primitives.ts
apps/web/vibes/soul/primitives/navigation/index.tsx

- Updates container queries for products in search results

audit: navigation

---

apps/web/vibes/soul/docs/featured-image.mdx
apps/web/vibes/soul/examples/primitives/button/index.tsx
apps/web/vibes/soul/examples/sections/featured-image/electric.tsx
apps/web/vibes/soul/examples/sections/featured-image/luxury.tsx
apps/web/vibes/soul/examples/sections/featured-image/warm.tsx
apps/web/vibes/soul/sections.ts
apps/web/vibes/soul/sections/featured-image/index.tsx

- adds css vars
- removes unnecessary `h-screen` on example page

audit: featured image

---

apps/web/vibes/soul/docs/discount.mdx
apps/web/vibes/soul/examples/sections/discount/index.tsx
apps/web/vibes/soul/sections.ts
apps/web/vibes/soul/sections/discount/index.tsx

- adds `localhost` support for storing dismiss state
- updates example with reset button

Audit discount

---

apps/web/vibes/soul/docs/maintenance.mdx
apps/web/vibes/soul/examples.ts
apps/web/vibes/soul/examples/pages/maintenance/index.tsx
apps/web/vibes/soul/examples/sections/maintenance/electric.tsx
apps/web/vibes/soul/examples/sections/maintenance/luxury.tsx
apps/web/vibes/soul/examples/sections/maintenance/warm.tsx
apps/web/vibes/soul/navigation.ts
apps/web/vibes/soul/sections.ts
apps/web/vibes/soul/sections/maintenance/index.tsx

- adds Maintenance to examples
- fixes logo not having height
- adds missing props to match closer to `Navigation`

audit: maintenance

---

apps/web/vibes/soul/docs/dynamic-form-section.mdx
apps/web/vibes/soul/sections.ts
apps/web/vibes/soul/sections/dynamic-form-section/index.tsx

audit: dynamic form section

---

apps/web/vibes/soul/docs/compare-section.mdx
apps/web/vibes/soul/docs/featured-product-carousel.mdx
apps/web/vibes/soul/docs/price-label.mdx
apps/web/vibes/soul/docs/product-carousel.mdx
apps/web/vibes/soul/examples/sections/compare-section/electric.tsx
apps/web/vibes/soul/examples/sections/compare-section/luxury.tsx
apps/web/vibes/soul/examples/sections/compare-section/warm.tsx
apps/web/vibes/soul/navigation.ts
apps/web/vibes/soul/sections.ts
apps/web/vibes/soul/sections/compare-section/index.tsx
apps/web/vibes/soul/sections/product-carousel/index.tsx

- removes "section" from navigation title
- incorporates `Skeleton` component

audit: compare section

---

apps/web/vibes/soul/docs/reviews.mdx
apps/web/vibes/soul/sections.ts
apps/web/vibes/soul/sections/reviews/index.tsx

- incorporates `Skeleton` component

audit: reviews

---

apps/web/vibes/soul/docs/footer.mdx
apps/web/vibes/soul/primitives/skeleton/index.tsx
apps/web/vibes/soul/sections.ts
apps/web/vibes/soul/sections/footer/index.tsx

- adds `max-w-full` to skeleton root to fix newfound error I came across where the skeleton width was extending outside the layout
- integrates `Skeleton` component
- removes `forwardRef`

audit: footer

---

apps/web/vibes/soul/docs/streamable.mdx

- add basic doc page for `Streamable`

Docs streamable

---

apps/web/vibes/soul/sections/card-carousel/index.tsx
apps/web/vibes/soul/sections/compare-section/index.tsx

- implements fix that caused flex containers to be incorrectly calculated

fix: overlapping issue in carousel flex containers

---

apps/web/vibes/soul/docs/button.mdx
apps/web/vibes/soul/examples/primitives/button/index.tsx
apps/web/vibes/soul/primitives/button/index.tsx

- Add `danger` prop to button
- Ensure hover styles don't apply when disabled

feat: Button - add 'danger' prop, fix disable hover

---

apps/web/vibes/soul/docs/card-carousel.mdx
apps/web/vibes/soul/docs/compare-card.mdx
apps/web/vibes/soul/docs/compare-section.mdx
apps/web/vibes/soul/docs/featured-card-carousel.mdx
apps/web/vibes/soul/examples/sections/card-carousel/electric.tsx
apps/web/vibes/soul/examples/sections/card-carousel/luxury.tsx
apps/web/vibes/soul/examples/sections/card-carousel/warm.tsx
apps/web/vibes/soul/examples/sections/featured-card-carousel/electric.tsx
apps/web/vibes/soul/examples/sections/featured-card-carousel/luxury.tsx
apps/web/vibes/soul/examples/sections/featured-card-carousel/warm.tsx
apps/web/vibes/soul/primitives/card/index.tsx
apps/web/vibes/soul/primitives/compare-card/index.tsx
apps/web/vibes/soul/sections/card-carousel/index.tsx
apps/web/vibes/soul/sections/compare-section/index.tsx
apps/web/vibes/soul/sections/featured-card-carousel/index.tsx

- changes type `CardWithId` to `CardContent`
- changes type `CompareCardWithId` to `CompareProduct`

fix: type CardWithId and CompareCardWithId

---

.github/dependabot.yml

Dependabot config for software composition analysis

feat: Adding dependabot config

---

apps/web/app/(marketing)/page.tsx

- centers the VIBES logo in the header
Before:
After:
https://github.com/user-attachments/assets/72d95bcc-c31d-4d92-aa10-3fd25e0cb69c

style: logo centering in site header

---

apps/web/app/(marketing)/layout.tsx

- removes "Coming soon" from site meta title
- formats Vibes to VIBES

fix: site meta title

---

apps/web/vibes/soul/docs/product-detail.mdx
apps/web/vibes/soul/sections/product-detail/index.tsx

docs: fix additionalInformationTitle typo

---

apps/web/vibes/soul/docs/electric.mdx
apps/web/vibes/soul/docs/luxury.mdx
apps/web/vibes/soul/docs/warm.mdx

- removes descriptions for style pages in docs

docs: remove description from style pages

---

apps/web/vibes/soul/docs/button-link.mdx
apps/web/vibes/soul/primitives/button-link/index.tsx

- renames `--button-link` to `--button` in the `ButtonLink` component so when the user changes their buttons styles in the site theme it will update both components at the same time.

feat: rename css vars for ButtonLink

---

apps/web/vibes/soul/primitives/chip/index.tsx

- adds CSS vars to chip
- exports named interface
https://github.com/user-attachments/assets/48f64cdf-e369-49a8-afb2-437559b16dd1

feat: add css vars to chip

---

apps/web/vibes/soul/examples/primitives/navigation/actions.ts

- binds `brand` to server action to ensure the server action is aware of the variable
Video from the deployed site
https://github.com/user-attachments/assets/6cf20fef-e17a-4453-9454-dbbc96a73733

fix: brand param not binding to searchAction

---

apps/web/vibes/soul/primitives/navigation/index.tsx
apps/web/vibes/soul/sections/cart/client.tsx
apps/web/vibes/soul/sections/cart/index.tsx
apps/web/vibes/soul/sections/countdown/index.tsx
apps/web/vibes/soul/sections/forgot-password/forgot-password-form.tsx
apps/web/vibes/soul/sections/sign-in/sign-in-form.tsx

- removes deprecated `flex-grow` and `flew-shrink` Tailwind classses

feat: remove deprecated flex-grow and flex-shrink classes

---

apps/web/vibes/soul/docs/inline-email-form.mdx
apps/web/vibes/soul/docs/swatch-radio-group.mdx
apps/web/vibes/soul/docs/textarea.mdx
apps/web/vibes/soul/form/swatch-radio-group/index.tsx
apps/web/vibes/soul/form/textarea/index.tsx
apps/web/vibes/soul/form/toggle-group/index.tsx
apps/web/vibes/soul/sections/inline-email-form/index.tsx

- fixes typos for incorrect CSS vars

fix: css vars for borders

---

apps/web/vibes/soul/docs/tabs.mdx
apps/web/vibes/soul/examples.ts
apps/web/vibes/soul/examples/primitives/tabs/index.tsx
apps/web/vibes/soul/navigation.ts
apps/web/vibes/soul/primitives.ts
apps/web/vibes/soul/primitives/compare-card/index.tsx
apps/web/vibes/soul/primitives/tabs/index.tsx
pnpm-lock.yaml

- adds `Tabs` component
- adds docs for `Tabs` component
https://github.com/user-attachments/assets/daf4cf45-53e9-4fb3-a00a-c094e3051380

feat: add Tabs component and docs

---

apps/web/vibes/soul/primitives/compare-drawer/index.tsx

- adds border color to `CompareDrawer`

feat: add border color to compare drawer

---

apps/web/vibes/soul/docs/number-input.mdx
apps/web/vibes/soul/docs/sign-in.mdx
apps/web/vibes/soul/form/number-input/index.tsx
apps/web/vibes/soul/sections/sign-in/index.tsx

- adds missing border color on sign-in and number input

fix: missing border colors on number input and sign-in

---

apps/web/vibes/soul/form/card-radio-group/index.tsx
apps/web/vibes/soul/sections/product-detail/product-detail-form.tsx
apps/web/vibes/soul/sections/product-detail/schema.ts

In some cases, the option can have no image.

feat: make image optional for card radio group

---

apps/web/vibes/soul/docs/input.mdx
apps/web/vibes/soul/docs/number-input.mdx
apps/web/vibes/soul/examples/form/number-input/index.tsx
apps/web/vibes/soul/form/number-input/index.tsx

- fixes vars for `Input` and `NumberInput`
- updates docs for `Input` and `NumberInput`

fix: wrong fallback values for vars, docs, and examples

---

apps/web/vibes/soul/sections/product-detail/product-detail-form.tsx

Missing field in product details form.

feat: add date field to product details form

---

apps/web/vibes/soul/sections/product-detail/product-detail-form.tsx
apps/web/vibes/soul/sections/product-detail/schema.ts

Missing textarea field in product details forms

feat: add textarea field to product details form

---

apps/web/package.json

- updates the package.json `build` script to include registry build

feat: update build script to include registry build:
