apps/web/vibes/soul/form/swatch-picker/index.tsx

+ Updates SwatchPicker to accept options with hex color or image.
+ Uses  Radix's `RadioGroup` to append input elements inside forms.
+ Modifies styles to match designs.
+ Fixes errors prop and styles.

feat: adds SwatchPicker form input

---

apps/web/vibes/soul/docs/form.mdx
apps/web/vibes/soul/examples/form.tsx
apps/web/vibes/soul/form/date-picker/index.tsx
apps/web/vibes/soul/form/input/index.tsx
apps/web/vibes/soul/navigation.ts

> [!NOTE]
> Builds off https://github.com/makeswift/vibes/pull/250. Review last commit.
- Adds `DatePicker` form input that uses the `Calendar` and `Input` primitives. Supports `defaultValue` or controlled state. Single selection.
- Adds `Form` section in navigation (not sure if this is what we want).

 feat: adds DatePicker form input

---

apps/web/vibes/soul/examples/pages/blog/index.tsx
apps/web/vibes/soul/examples/pages/blog/post/electric.tsx
apps/web/vibes/soul/examples/pages/blog/post/luxury.tsx
apps/web/vibes/soul/examples/pages/blog/post/warm.tsx
apps/web/vibes/soul/examples/pages/home/electric.tsx
apps/web/vibes/soul/examples/pages/home/luxury.tsx
apps/web/vibes/soul/examples/pages/home/warm.tsx
apps/web/vibes/soul/examples/pages/not-found/electric.tsx
apps/web/vibes/soul/examples/pages/not-found/luxury.tsx
apps/web/vibes/soul/examples/pages/not-found/warm.tsx
apps/web/vibes/soul/examples/pages/product/electric.tsx
apps/web/vibes/soul/examples/pages/product/luxury.tsx
apps/web/vibes/soul/examples/pages/product/warm.tsx
apps/web/vibes/soul/examples/pages/products/electric.tsx
apps/web/vibes/soul/examples/pages/products/luxury.tsx
apps/web/vibes/soul/examples/pages/products/warm.tsx
apps/web/vibes/soul/examples/primitives/navigation/electric.tsx
apps/web/vibes/soul/examples/primitives/navigation/luxury.tsx
apps/web/vibes/soul/examples/primitives/navigation/warm.tsx
apps/web/vibes/soul/pages/cart/index.tsx
apps/web/vibes/soul/primitives/navigation/index.tsx

Just like `accountHref` and `cartHref`, we need to allow passing in a custom search href the form submits too.

feat: add missing searchHref prop in Navigation

---

apps/web/vibes/soul/primitives/banner/index.tsx

HTML spec disallows nesting `<p>`s and `<div>`s inside of a `<p>`.

fix(Banner): allow `children` to be a `<p>` or another `<div>`

---

apps/web/vibes/soul/sections/products-list-section/sorting.tsx

Fixes issue of changing sort param no retriggering server render by passing in `shallow: false` as an option.

fix: trigger server render on sort

---

apps/web/vibes/soul/form/select/index.tsx

Sets a z-index to prevent select from being hidden by other elements.
Before:
https://github.com/user-attachments/assets/b1db962f-b8b9-455c-9123-3bec2100839c
After:
https://github.com/user-attachments/assets/ca1177e3-4eec-4b43-8c16-acbab613d1b3

fix: add z-index to select to prevent it from being hidden

---

apps/web/vibes/soul/primitives/cursor-pagination/index.tsx

For cursor navigation we either want an `after` or `before`, not both.
Before:
https://github.com/user-attachments/assets/e7189cd1-ebbf-47df-8197-211073c94ed5
After:
https://github.com/user-attachments/assets/1a76128f-846a-418e-913d-368e724c8254

fix: cursor navigation by remove unused param

---

apps/web/vibes/soul/sections/reviews/index.tsx

- Wraps `<Reviews />` in `Suspense` boundary and internally resolves Promises if passed.
- Streams in data inside components for total count and average rating.
- Adds missing `reviewsLabel`.

feat: add streamable props in Reviews section

---

apps/web/vibes/soul/sections/slideshow/index.tsx

- Fixes issue where the slide was not visible when the button was focused
- Replaces `text-pretty` with `text-balance` for text-wrapping
https://github.com/user-attachments/assets/96060633-40b8-4585-8572-5d4d0019c6f1

fix: slide not in view when element inside is focused

---

.gitignore
apps/web/components/navigation/header.tsx
apps/web/lib/env.ts
apps/web/next-sitemap.config.js
apps/web/package.json

- update sitemap to ignore paths with `/preview`
- remove write API key for algolia and use read only key
- ignore `robots.txt` so it is generated on build
- update package.json `build` script to also call `sitemap` script (wasn't be called automatically in `postbuild` script)
- reference `VERCEL_URL` environment variable instead of hard-coded vibes.site url - this will allow us to test crawlers on preview deploy links if we want to

Fix Sitemap and Algolia Search

---

apps/web/app/(preview)/layout.tsx
apps/web/package.json
apps/web/vibes/soul/docs/toaster.mdx
apps/web/vibes/soul/examples.ts
apps/web/vibes/soul/examples/primitives/alert/index.tsx
apps/web/vibes/soul/examples/primitives/toaster/index.tsx
apps/web/vibes/soul/navigation.ts
apps/web/vibes/soul/primitives/alert/index.tsx
apps/web/vibes/soul/primitives/toaster/index.tsx
pnpm-lock.yaml

- Adds the `Toaster` primitive that uses [Sonner](apps/web/vibes/soul/sections/subscribe/index.tsx) for toasts.
- Customize Toaster.
- Updated the docs to include this new primitive.
- Add primitive to preview to enable use of `toast` in other components.
https://github.com/user-attachments/assets/635b1c8d-9862-4a69-b9f6-bd9905db4d34
> [!IMPORTANT]  
> There is a divergence from the proposed designs in how we handle the close button:
`Sonner` has it on the corner since the toast can have an action on the right side of the toast. 
The proposed designs has the close/dismiss button as an action:
I feel it may be important to retain the action prop api for Toast so I think it is a better implementation to keep the close button in the corner as it currently works from the box in Sonner, but I …

feat: add Toaster primitive for Soul

---

apps/web/vibes/soul/examples/primitives/inline-email-form/actions.ts
apps/web/vibes/soul/examples/primitives/inline-email-form/index.tsx
apps/web/vibes/soul/examples/sections/subscribe/index.tsx
apps/web/vibes/soul/primitives/inline-email-form/index.tsx
apps/web/vibes/soul/sections/subscribe/index.tsx

+ Update component to show toast on success
+ Add `successMessage` prop
+ Add `dismissLabel` prop
+ Change revalidation `onBlur` (this felt better for me)
As a side note: 1password is trying to save this field.
https://github.com/user-attachments/assets/c65ca487-d4fd-424d-b351-3e0bd76fcb19

feat: update subscribe section to show toast and intl props

---

apps/web/vibes/soul/examples/primitives/products-carousel/index.tsx
apps/web/vibes/soul/examples/sections/featured-products-carousel/index.tsx
apps/web/vibes/soul/primitives/product-card/index.tsx
apps/web/vibes/soul/primitives/products-carousel/index.tsx
apps/web/vibes/soul/sections/featured-products-carousel/index.tsx

- Adds empty state to the `ProductsCarousel` component
- Simplifies examples for the `FeaturedProductsCarousel` by using a single component to handle loading and empty states
- Adds optional `loading` prop to the `ProductsCarousel` component to remove animation on the empty state
- Removes separate components for rendering `ProductsCarouselSkeleton` and `ProductsCarouselEmptyState`
https://github.com/user-attachments/assets/7394b0d2-a8a0-4f87-95fe-13ec3510154e

feat: add empty state to ProductsCarousel

---

apps/web/vibes/soul/primitives/navigation/index.tsx

For accessibility purposes, added an `aria-label` to the Link in Navigation and expose this prop to be passed in.

fix: add aria-label to logo link in Navigation

---

apps/web/vibes/soul/primitives/products-carousel/index.tsx

- Fixes import for `Stream` and `Streamable` in the `ProductsCarousel`
Locally

fix: imports for Stream and Streamable in ProductsCarousel

---

apps/web/vibes/soul/examples/sections/featured-products-carousel/index.tsx
apps/web/vibes/soul/examples/sections/featured-products-list/electric.tsx
apps/web/vibes/soul/examples/sections/featured-products-list/luxury.tsx
apps/web/vibes/soul/examples/sections/featured-products-list/warm.tsx
apps/web/vibes/soul/examples/sections/products-list-section/electric.tsx
apps/web/vibes/soul/examples/sections/products-list-section/luxury.tsx
apps/web/vibes/soul/examples/sections/products-list-section/warm.tsx
apps/web/vibes/soul/primitives/products-carousel/index.tsx
apps/web/vibes/soul/primitives/products-list/index.tsx
apps/web/vibes/soul/sections/featured-products-carousel/index.tsx
apps/web/vibes/soul/sections/featured-products-list/index.tsx
apps/web/vibes/soul/sections/products-list-section/index.tsx

- Adds `count` prop to `ProductList` so sections that use this component can render a custom number of empty state cards 
- Adds `emptyStateTitle` and `emptyStateDescription` to `ProductsListSection`
https://github.com/user-attachments/assets/bdfb2cb7-ecc0-4377-a30d-837e3528104f

feat: add empty state to product list section

---

apps/web/vibes/soul/primitives/breadcrumbs/index.tsx

- Uses `ol` and `li` elements for breadcrumbs navigations
- Add accessibility improvements
Locally

feat: improve accessibility and use ol and li elements

---

apps/web/vibes/soul/sections/product-detail/index.tsx
apps/web/vibes/soul/sections/product-detail/product-detail-form.tsx

Adds `quantityLabel` prop to ProductDetail that is then forwarded to form and set as an `aria-label` to the quantity field since we don't have a visible label.

feat: add accessible props to ProductDetail

---

apps/web/vibes/soul/primitives/animated-link/index.tsx
apps/web/vibes/soul/primitives/breadcrumbs/index.tsx

- Updates skeleton height
- Incorporates `AnimatedLink` component into breadcrumbs
https://github.com/user-attachments/assets/4839ae06-c8c0-4210-9be1-af8fa528bb25

feat: update breadcrumbs to use AnimatedLink

---

apps/web/vibes/soul/primitives/animated-link/index.tsx
apps/web/vibes/soul/primitives/breadcrumbs/index.tsx

- Avoids layout shift when no breadcrumbs are present by adding an empty `div`
- Removes padding from animate links to avoid extra height being added
https://github.com/user-attachments/assets/0bcb17b5-3f4e-497c-ab63-07fdf0065361

feat: avoid layout shift when breadcrumbs are empty

---

apps/web/vibes/soul/primitives/button/index.tsx

It currently looks visually disabled but it is not disabled. This properly disables the button.

fix: allow disabling the Button component

---

apps/web/vibes/soul/primitives/navigation/index.tsx

- Moves empty state labels to server action so that they can depend on server action parameters (e.g., search term)
- Changes some HTML elements for better a11y
- Avoids showing error and empty states when we're fetching new search results
https://github.com/user-attachments/assets/07c47ea8-0e18-45df-ba6c-0af143a05679

Better error handling, a11y, and i18n for header search

---

apps/web/vibes/soul/examples/sections/product-detail/action.ts
apps/web/vibes/soul/primitives/alert/index.tsx
apps/web/vibes/soul/primitives/toaster/index.tsx
apps/web/vibes/soul/sections/product-detail/index.tsx
apps/web/vibes/soul/sections/product-detail/product-detail-form.tsx

This will show a toast of a simple string when product is added successfully. We still need to think about how to pass in string interpolation so that we can render a more custom message with a link that understand the quantity added.

feat: show toasts on successfully adding a product

---

apps/web/vibes/soul/sections/product-detail/index.tsx
apps/web/vibes/soul/sections/product-detail/product-detail-form.tsx

This allows disabling the button from an API responses as well as setting the label depending on the status.

feat: stream in submit button label and disabled status

---

apps/web/app/(preview)/layout.tsx
apps/web/package.json
pnpm-lock.yaml

Updates `nuqs`, the library we use for URL search params, to the latest version

feat: upgrade nuqs to latest version

---

apps/web/vibes/soul/examples/pages/blog/post/electric.tsx
apps/web/vibes/soul/examples/pages/blog/post/luxury.tsx
apps/web/vibes/soul/examples/pages/blog/post/warm.tsx
apps/web/vibes/soul/sections/blog-post-content/index.tsx

When working on implementing BlogPostContent into catalyst, I noticed that `breadcrumbs` were always static because it is not a prop on the component.
We should allow breadcrumbs as a prop so that they can be provided to the component.
- Add `breadcrumbs` as prop
- Make `author` optional

feat: add breadcrumbs as prop to BlogPostContent, make 'author' optional

---

apps/web/vibes/soul/form/button-radio-group/index.tsx
apps/web/vibes/soul/form/card-radio-group/index.tsx
apps/web/vibes/soul/form/radio-group/index.tsx
apps/web/vibes/soul/form/select/index.tsx
apps/web/vibes/soul/form/swatch-radio-group/index.tsx
apps/web/vibes/soul/sections/product-detail/index.tsx
apps/web/vibes/soul/sections/product-detail/product-detail-form.tsx

This change allows prefetching to happen when multi select form elements are moused over.  This feature can be enabled by passing `prefetch=true`.
https://github.com/user-attachments/assets/f7625fc0-fffa-4f84-864e-b3ac0857b689

feat: add prefetching to product detail form

---

apps/web/vibes/soul/form/number-input/index.tsx
apps/web/vibes/soul/primitives/dynamic-form/index.tsx
apps/web/vibes/soul/primitives/dynamic-form/schema.ts
apps/web/vibes/soul/sections/product-detail/product-detail-form.tsx
apps/web/vibes/soul/sections/product-detail/schema.ts

`disabled` was undefined so the active/disabled classes were not being properly set.
Before:
After:

fix: properly handle disabled state in NumberInput

---

apps/web/vibes/soul/examples/sections/account-settings-section/actions.ts
apps/web/vibes/soul/examples/sections/account-settings-section/index.tsx
apps/web/vibes/soul/examples/sections/address-list-section/index.tsx
apps/web/vibes/soul/examples/sections/order-list-section/electric.tsx
apps/web/vibes/soul/sections/account-settings-section/index.tsx
apps/web/vibes/soul/sections/account-settings-section/schema.ts
apps/web/vibes/soul/sections/account-settings-section/update-account-form.tsx

- Adds default values to be passed into the update account settings form.
- Adds a company field to the form
- Uses optimistic updates when submitting the update customer form action.
- Updates some examples to use the `AccountLayout` plus real links (to prevent duplicate React keys warning).
https://github.com/user-attachments/assets/10427720-3359-4096-9114-b993badeeba4

feat: add default props and optimistic update to account settings

---

apps/web/vibes/soul/sections/product-detail/index.tsx
apps/web/vibes/soul/sections/product-detail/product-detail-form.tsx
apps/web/vibes/soul/sections/product-detail/schema.ts

+ Updated skeletons to prevent issues when importing to Catalyst
+ Add `FormStateInput` to hold state between reload
+ Disable deep linking for non multi select inputs that could fetch new variants.
+ Prevents entire form rerenders when typing on inputs.
+ Also fixes an issue with uncontrolled components when they default to empty string

feat: disable deep linking for non multi select inputs

---

apps/web/vibes/soul/examples/pages/blog/index.tsx
apps/web/vibes/soul/examples/sections/blog-post-list/index.tsx
apps/web/vibes/soul/examples/sections/featured-blog-post-list/index.tsx
apps/web/vibes/soul/primitives/blog-post-card/index.tsx
apps/web/vibes/soul/sections/blog-post-content/index.tsx
apps/web/vibes/soul/sections/blog-post-list/index.tsx
apps/web/vibes/soul/sections/featured-blog-post-list/index.tsx

- Ensure `posts` property is `Streamable<BlogPost[]>` on FeaturedBlogPostList and BlogPostList
- Update all previews with a timeout to ensure the loading state is displayed in the docs
- Add `object-cover` style to BlogPostCard to prevent image stretching
- Minor refactoring

feat: use streamable props on BlogPostList

---

apps/web/vibes/soul/examples/sections/address-list-section/actions.ts
apps/web/vibes/soul/examples/sections/address-list-section/index.tsx
apps/web/vibes/soul/sections/address-list-section/index.tsx

> [!TIP]
> Hide whitespace might help reviewing.
Adds two bits of functionality to the `AddressListSection` component:
- Makes setting the default address optional as some systems may not have that ability.
- Adds a `minimumAddressCount` prop to enforce how many addresses can be deleted.
Below is the matrix on the prop logic:
| `defaultAddress` value | Functionality |
| ----------------------- | ------------- |
| `undefined`                   | No default address functionality will be shown |
| `{ id: null }`                    | Shows the `Set Default` button in a situation where a customer doesn't have a default address set |
| `{ id: '1' }`                     | Renders the `Set Default` button on every address that is not the default. Shows the default label on the default address. | …

feat: address-list-section updates

---

apps/web/vibes/soul/sections/reviews/index.tsx

With the `Stream` pattern, having a wrapping component is not needed.

fix: delete wrapping component in Reviews

---

apps/web/vibes/soul/sections/product-detail/index.tsx

I accidentally removed it when I just needed to change the max-width to match the new designs:

fix: add max-width to ProductDetails

---

apps/web/vibes/soul/form/select/index.tsx
apps/web/vibes/soul/sections/products-list-section/index.tsx
apps/web/vibes/soul/sections/products-list-section/sorting.tsx

- Updates `Sorting` component to use `Stream` instead of `Suspense`
- Adds `focus-visible` styles to `SelectPrimitive.Item`
- Updates imports to use `@/vibes`
- Adds `placeholder` prop into `ProductListSection`, `Sorting`, and `Select`
- Adds optional `hideLabel` prop to `Select`
- Passes `Promise.all` into stream values
This component encapsulates `Stream` inside of `Sorting` instead of using `Stream` inside the `ProductsListSection`. Is there a reason we don't do this for the other components like `Breadcrumbs`?
The component rendered inside the `Stream` is called `SortingResolved.` I think this makes the streamable pattern very clear to the user.
https://github.com/user-attachments/assets/b333ba91-6c63-41ca-8625-7f9d5bafa30a

feat: use Stream inside Sorting and update props and focus-visible styles

---

apps/web/vibes/soul/form/checkbox/index.tsx
apps/web/vibes/soul/form/range-input/index.tsx
apps/web/vibes/soul/primitives/accordions/index.tsx
apps/web/vibes/soul/primitives/products-list/index.tsx
apps/web/vibes/soul/sections/products-list-section/filters-panel.tsx
apps/web/vibes/soul/sections/products-list-section/index.tsx

This PR adds various improvements for the products list section, primarily for a11y.
Once we address color contrast issues we should reach a score of 100.

a11y improvements for products list section

---

apps/web/vibes/soul/sections/products-list-section/filter-parsers.ts
apps/web/vibes/soul/sections/products-list-section/filters-panel.tsx
apps/web/vibes/soul/sections/products-list-section/index.tsx

https://github.com/user-attachments/assets/8b72b25f-fcd4-47da-a68b-7d093c49805a

feat: add link-group PLP filter

---

apps/web/.eslintrc.json
apps/web/vibes/soul/examples/pages/error/index.tsx
apps/web/vibes/soul/sections/error/index.tsx

I noticed NextJS requires Error page to be a client component, so we need to use an onClick handler instead of an href.
Updated `Error` section to allow a function to be passed in rather than a string.
https://nextjs.org/docs/app/building-your-application/routing/error-handling#using-error-boundaries

feat: update Error to use click event handler

---

apps/web/vibes/soul/sections/order-list-section/index.tsx
apps/web/vibes/soul/sections/order-list-section/order-list-item.tsx
apps/web/vibes/soul/sections/order-list-section/order-list-line-item.tsx
apps/web/vibes/soul/sections/order-list-section/order-list.tsx

- Moves the margin from the subtitle onto the price label to keep margin consistency when there is no `subtitle` for a line item.
- Adds label props for the hardcoded text to provide the ability to localize messages.

feat(orders): update orders-list component

---

apps/web/vibes/soul/form/button-radio-group/index.tsx
apps/web/vibes/soul/form/card-radio-group/index.tsx
apps/web/vibes/soul/form/checkbox-group/index.tsx
apps/web/vibes/soul/form/radio-group/index.tsx
apps/web/vibes/soul/form/swatch-radio-group/index.tsx
apps/web/vibes/soul/form/toggle-group/index.tsx

Fixes an issue in Lighthouse with mismatched aria roles:
Setting this is not required, any accessibility attribute is handled by radix, if any.

fix: remove unecessary aria-role in radio groups

---

apps/web/vibes/soul/form/checkbox/index.tsx

Adds the `id` + `htmlFor` for the checkbox so that the label is clickable.
https://github.com/user-attachments/assets/fe0b2594-72d9-464e-8957-663864b7194e

fix(soul): accessibility for checkbox

---

apps/web/vibes/soul/sections/product-detail/product-detail-form.tsx

Even though we generate default values:
```ts
const defaultValue = fields.reduce<{
[Key in keyof SchemaRawShape]?: z.infer<SchemaRawShape[Key]>;
}>(
(acc, field) => ({
...acc,
[field.name]: params[field.name] ?? field.defaultValue ?? '',
}),
{ quantity: 1 },
);
```
Example of defaultValue object:
```
{
'108': '99',
'109': '106',
'130': '',
'133': '137',
'134': '140',
'135': 'false',
'136': '',
'137': '',
'138': '',
'140': '',
quantity: 1
}
```
For some reason, `useForm` sets empty strings as `undefined` for `defaultValue/initialValue`. Problem is we control all these fields in this form, so we can't change from `uncontrolled => controlled` without a warning.
Basically, it transforms to:
```
{
'108': '99',
'109': '106',
'130': undefined,
'133': '137',
'134': '140',
'135': 'false',
'136': …
```

fix: force default value for inputs in PDP

---

apps/web/vibes/soul/examples/sections/order-details-section/electric.tsx
apps/web/vibes/soul/examples/sections/order-details-section/luxury.tsx
apps/web/vibes/soul/examples/sections/order-details-section/warm.tsx
apps/web/vibes/soul/sections/order-details-section/index.tsx

This change is due to how ecommerce orders are actually handled. For example, when you place an order you can ship X items to one address, and ship Y items to another. This is also called consignments, but to make it more friendly to the end user, I opted for the name `destinations` instead.
In ecomm, each destination can have multiple shipments. This all depends on how the order is fulfilled by each merchant. Some products need to be sent in multiple boxes (e.g. furniture) or send in partial shipments (e.g. as products arrive at the warehouse). I refactored the schema to handle multiple shipments under each destination.
Added the ability to handle links in the tracking information field. With this came renaming `id` to `number` as it might cause some confusion for developers that they …

feat(soul): refactor order detail page

---

apps/web/vibes/soul/form/select/index.tsx

Adds some layout CSS to prevent the select from shrinking in side-by-side rows:
Tested the pages that use this component to ensure there aren't any regressions.
Before:
After:
Before:
After:

feat(soul): add layout CSS to Select component

---

apps/web/vibes/soul/form/card-radio-group/index.tsx
apps/web/vibes/soul/primitives/blog-post-card/index.tsx
apps/web/vibes/soul/primitives/card/index.tsx
apps/web/vibes/soul/primitives/compare-card/index.tsx
apps/web/vibes/soul/primitives/logo/index.tsx
apps/web/vibes/soul/primitives/navigation/index.tsx
apps/web/vibes/soul/primitives/product-card/index.tsx
apps/web/vibes/soul/primitives/products-carousel/index.tsx
apps/web/vibes/soul/primitives/products-list/compare-drawer.tsx
apps/web/vibes/soul/primitives/products-list/index.tsx
apps/web/vibes/soul/sections/cart/index.tsx
apps/web/vibes/soul/sections/checkout/index.tsx
apps/web/vibes/soul/sections/compare-section/index.tsx
apps/web/vibes/soul/sections/footer/index.tsx
apps/web/vibes/soul/sections/order-details-section/index.tsx
apps/web/vibes/soul/sections/order-list-section/order-list-line-item.tsx
apps/web/vibes/soul/sections/product-detail/product-gallery.tsx
apps/web/vibes/soul/sections/slideshow/index.tsx
apps/web/vibes/soul/sections/subscribe/index.tsx

- Add a `sizes` prop where missing
- Make `sizes` prop match media queries where needed
- Use `priority` only for first images, when needed

feat: optimize images

---

apps/web/vibes/soul/sections/sticky-sidebar-layout/index.tsx

When using an Image inside of a StickySidebarLayout a min width was being set preventing it from shrinking in a flex layout. This PR fixes this by setting a min width of 0 on the columns in the StickySidebarLayout component.

fix: sticky sidebar layout overflow

---

apps/web/vibes/soul/primitives/navigation/index.tsx

Sucessor to #472
Adds the currency dropdown to Navigation, that triggers a server action in a form, like locales.

feat: add currency dropdown to Navigation

---

.vscode/settings.json

We had reports that files weren't being formatted on save so I'm adding
this option for a consistent experience for VS Code users.

chore: enable format on save

---

apps/web/vibes/soul/examples/primitives/products-carousel/electric.tsx
apps/web/vibes/soul/examples/primitives/products-carousel/luxury.tsx
apps/web/vibes/soul/examples/primitives/products-carousel/warm.tsx
apps/web/vibes/soul/primitives/card-carousel/index.tsx
apps/web/vibes/soul/primitives/card/index.tsx
apps/web/vibes/soul/primitives/product-card/index.tsx
apps/web/vibes/soul/primitives/products-carousel/index.tsx
apps/web/vibes/soul/primitives/products-list/index.tsx
apps/web/vibes/soul/primitives/skeleton/index.tsx
apps/web/vibes/soul/sections/featured-products-carousel/index.tsx
apps/web/vibes/soul/sections/featured-products-list/index.tsx
apps/web/vibes/soul/sections/section-layout/index.tsx

This PR introduces a `Skeleton` primitive to VIBES that will help streamline the creation of skeleton loaders across the project. I'm also proposing a `Skeleton.Root` component to simplify creating component skeletons because it automatically handles accessibility and the `data-pending` pattern to handle skeleton animations.
This PR also promotes the `ProductsCarousel` to a section after discussing with the team that primitives should only be responsible for rendering data and that primitives should not compose other primitives.
- Provides `Skelton.Root` `Skeleton.Text` `Skelton.Box` and `Skeleton.Icon` components
- Simplifies the process of making skeletons accessible
- Relies on Tailwind classes to style the component rather than props that control the styles
- `characterCount` prop on …

feat: add Skeleton component and SkeletonWrapper component

---

apps/web/vibes/soul/docs/chip.mdx
apps/web/vibes/soul/examples.ts
apps/web/vibes/soul/examples/primitives/chip/index.tsx
apps/web/vibes/soul/navigation.ts
apps/web/vibes/soul/primitives/chip/index.tsx

Adds `Chip` primitive that will be used in `Cart` section.

feat: add Chip primitive

---

apps/web/vibes/soul/docs/accordion.mdx
apps/web/vibes/soul/examples.ts
apps/web/vibes/soul/examples/primitives/accordion/index.tsx
apps/web/vibes/soul/navigation.ts
apps/web/vibes/soul/primitives.ts
apps/web/vibes/soul/primitives/accordion/index.tsx
apps/web/vibes/soul/sections/product-detail/index.tsx
apps/web/vibes/soul/sections/products-list-section/filters-panel.tsx

- Renames `Accordions` to `Accordion`
- Renames `Accordion` to `AccordionItem`
https://github.com/user-attachments/assets/6ff4bde9-52bc-47e6-b16a-33650b58e238

fix: rename Accordions to Accordion

---

apps/web/vibes/soul/examples/primitives/badge/index.tsx
apps/web/vibes/soul/primitives/badge/index.tsx
apps/web/vibes/soul/primitives/product-card/index.tsx
apps/web/vibes/soul/sections/order-details-section/index.tsx

- Renames `variant` to `shape` and `color` to `variant` to match the existing naming pattern
- Changes `children` to be of type `string` 
- Exports interface
- Updates existing examples  
https://github.com/user-attachments/assets/264105b9-6ac7-4cd6-98b0-c84e7edfeedd

audit: badge component

---

apps/web/vibes/soul/primitives.ts
apps/web/vibes/soul/primitives/calendar/index.tsx

- Moves `Calendar` into its own folder like the rest of the components
- Updates config files to the new location
- Export `CalendarProps` type – was getting an error when trying to use `interface`
- Updates CSS variables

audit: calendar

---

apps/web/vibes/soul/examples/primitives/card/index.tsx
apps/web/vibes/soul/primitives/blog-post-card/index.tsx
apps/web/vibes/soul/primitives/card/index.tsx
apps/web/vibes/soul/primitives/product-card/index.tsx

- Removed `w-full` from `Card` component–I think we should avoid doing this, especially if we want the `className` prop to be used sparingly for things like adjusting `margin`
- Made card an `article` element
- Set the `Link` component to be absolutely positioned
- Added focus styles to `Link`
- Added offset color styles for light vs dark variants
- Added some CSS variables
- Removed rounded border from CSS variables–I'd like to stick to just colors and fonts for this first release
- Fixed a quick error in `BlogPostCard` where I was passing in `className` in the `Link` component still
- Fixed random ESLint rules about prop order

audit: card

---

apps/web/vibes/soul/docs/carousel.mdx
apps/web/vibes/soul/docs/skeleton.mdx
apps/web/vibes/soul/docs/streamable.mdx
apps/web/vibes/soul/examples/pages/blog/index.tsx
apps/web/vibes/soul/examples/primitives/card-carousel/electric.tsx
apps/web/vibes/soul/examples/primitives/card-carousel/luxury.tsx
apps/web/vibes/soul/examples/primitives/card-carousel/warm.tsx
apps/web/vibes/soul/examples/sections/blog-post-list/index.tsx
apps/web/vibes/soul/examples/sections/featured-blog-post-list/index.tsx
apps/web/vibes/soul/navigation.ts
apps/web/vibes/soul/primitives.ts
apps/web/vibes/soul/primitives/blog-post-card/index.tsx
apps/web/vibes/soul/primitives/blog-post-carousel/index.tsx
apps/web/vibes/soul/primitives/card/index.tsx
apps/web/vibes/soul/primitives/products-carousel/index.tsx
apps/web/vibes/soul/primitives/skeleton/index.tsx
apps/web/vibes/soul/sections.ts
apps/web/vibes/soul/sections/blog-post-list/index.tsx
apps/web/vibes/soul/sections/card-carousel/index.tsx
apps/web/vibes/soul/sections/featured-blog-post-carousel/index.tsx
apps/web/vibes/soul/sections/featured-blog-post-list/index.tsx
apps/web/vibes/soul/sections/featured-card-carousel/index.tsx

- Renamed existing types that used `WithKey` to `WithId`
- Reworked `CarouselEmptyState` to include new CSS variables for styling light and dark color schemes
- Moved to Sections
- Renamed "Components" to "Primitives" in site navigation
I noticed existing components used `id` for more than just passing into the `key` for components. I rather keep the data and naming consistent, so I reverted some data and components that are outside the `CardCarousel`

audit:card-carousel

---

apps/web/vibes/soul/examples/pages/cart/electric.tsx
apps/web/vibes/soul/examples/pages/cart/luxury.tsx
apps/web/vibes/soul/examples/pages/cart/warm.tsx
apps/web/vibes/soul/examples/sections/cart/actions.ts
apps/web/vibes/soul/examples/sections/cart/electric.tsx
apps/web/vibes/soul/examples/sections/cart/luxury.tsx
apps/web/vibes/soul/examples/sections/cart/warm.tsx
apps/web/vibes/soul/form/input/index.tsx
apps/web/vibes/soul/primitives/chip/index.tsx
apps/web/vibes/soul/sections/cart/client.tsx
apps/web/vibes/soul/sections/cart/coupon-code-form.tsx
apps/web/vibes/soul/sections/cart/coupon-code-form/coupon-chip.tsx
apps/web/vibes/soul/sections/cart/coupon-code-form/index.tsx
apps/web/vibes/soul/sections/cart/schema.ts

Adds coupon code form to Cart section.
In coupon code you can:
1. Apply a coupon code
2. Remove existing coupon codes
Exposed props to Cart section to pass to the form. Updated examples to include coupon code form.
https://github.com/user-attachments/assets/4d5e020a-7696-4977-94ce-da2d166a45cc

feat: add coupon code form to Cart

---

apps/web/vibes/soul/primitives/banner/index.tsx

- Change the type from `ForwardRef` to `Ref` since we are removing `forwardRef` from our components

fix: ForwardRef type in Banner

---

apps/web/vibes/soul/examples/primitives/cursor-pagination/index.tsx
apps/web/vibes/soul/primitives/cursor-pagination/index.tsx

- Updated `CursorPagination` to use `Stream`
- Updated `CursorPaginationSkeleton` to use `Skeleton` primitive
- Added CSS vars
- Changed `startCursor` and `endCursor` from optional since the default value would've been set to `null` anyway. Also, it's easier to understand what's going on in the example when `null` is passed in IMO.

audit: cursor pagination

---

apps/web/vibes/soul/docs/not-found.mdx
apps/web/vibes/soul/examples.ts
apps/web/vibes/soul/examples/sections/not-found/index.tsx
apps/web/vibes/soul/navigation.ts
apps/web/vibes/soul/sections.ts
apps/web/vibes/soul/sections/not-found/index.tsx

- adds `NotFound` placeholder doc
- exports prop interface

audit: not found

---

apps/web/vibes/soul/docs/icon-block.mdx
apps/web/vibes/soul/examples/sections/icon-block/index.tsx
apps/web/vibes/soul/sections.ts
apps/web/vibes/soul/sections/icon-block/index.tsx

- adds css vars
- simplifies some CSS choices like using `border` instead of a weird combo of `divider` and `border`

audit: icon block

---

apps/web/vibes/soul/primitives/skeleton/index.tsx
apps/web/vibes/soul/sections/footer/index.tsx

- Fixes issue where columns would stretch to fit the grid, which would create very large spaces between columns when there weren't a lot of columns.
- Removes `max-width` on `Skeleton.Root` which was causing issues when a container was using Flexbox.
https://github.com/user-attachments/assets/223ee861-37d4-42e3-a8f3-fa3a2b379c8f

fix: css grid for footer columns

---

apps/web/vibes/soul/primitives/button/index.tsx

Removes the `srOnlyText` button prop in favor of `aria-label`. `aria-label` provides better support for screen readers, rather than prefixing text before children.

chore(button): remove srOnlyText

---

apps/web/app/(marketing)/page.tsx
apps/web/components/navigation/chapter-select.tsx
apps/web/vibes/soul/index.ts

- adds correct CTA to docs on mobile
- replaces SOUL preview image in vibe selector drawer

fix: homepage mobile CTAs

---

apps/web/vibes/soul/examples/primitives/compare-drawer/electric.tsx
apps/web/vibes/soul/examples/primitives/compare-drawer/luxury.tsx
apps/web/vibes/soul/examples/primitives/compare-drawer/warm.tsx
apps/web/vibes/soul/examples/sections/compare-section/actions.ts
apps/web/vibes/soul/examples/sections/compare-section/electric.tsx
apps/web/vibes/soul/examples/sections/compare-section/luxury.tsx
apps/web/vibes/soul/examples/sections/compare-section/warm.tsx
apps/web/vibes/soul/primitives/compare-card/add-to-cart-form.tsx
apps/web/vibes/soul/primitives/compare-card/index.tsx
apps/web/vibes/soul/primitives/compare-card/schema.ts
apps/web/vibes/soul/primitives/compare-drawer/index.tsx
apps/web/vibes/soul/primitives/compare-drawer/loader.tsx
apps/web/vibes/soul/primitives/product-card/compare.tsx
apps/web/vibes/soul/primitives/product-card/index.tsx
apps/web/vibes/soul/sections/compare-section/index.tsx
apps/web/vibes/soul/sections/featured-product-list/index.tsx
apps/web/vibes/soul/sections/product-list-section/index.tsx
apps/web/vibes/soul/sections/product-list/index.tsx

- Adds compare drawer functionality to Product List section
- Instead of an action, it is now a link that redirect to specified url. Default is `/compare`.
- Compare section now is aware of showing buy buttons or links to product (for products with variants).

feat: add compare drawer functionality

---

apps/web/vibes/soul/lib/streamable.test.ts
apps/web/vibes/soul/lib/streamable.tsx

Backporting https://github.com/bigcommerce/catalyst/pull/2116 with a test.

fix(Streamable): preserve inputs identity if none of them is a promise

---

apps/web/vibes/soul/sections/product-detail/index.tsx

- adds prose class to `ProductDetails` description to support custom HTML
- removes the default `max-width` set by my prose
https://github.com/user-attachments/assets/3736fec4-ae89-4441-9b46-207dbae3d632

fix: missing prose class and max-width prose override

---

apps/web/vibes/soul/sections/product-detail/product-detail-form.tsx

- removes `router.refresh()` from the PDP form since it's specific to Catalyst

remove: refresh data cache to pdp form?

---

apps/web/vibes/soul/docs/not-found.mdx
apps/web/vibes/soul/sections/not-found/index.tsx

- adds `className` to `NotFound` to allow passing to `SectionLayout`
https://github.com/user-attachments/assets/7b94eb9c-da48-450a-9bd6-720cfcd9c099

feat: add className to NotFound component

---

apps/web/vibes/soul/primitives/reveal/index.tsx

- updates styles in `Reveal` component to have smaller text and button variants
- updates `Button` to `tertiary` variant

feat: update styles on Reveal component

---

apps/web/components/ui/table-of-contents.tsx
apps/web/vibes/soul/docs/compare-card.mdx
apps/web/vibes/soul/examples/primitives/compare-card/electric.tsx
apps/web/vibes/soul/examples/primitives/compare-card/luxury.tsx
apps/web/vibes/soul/examples/primitives/compare-card/warm.tsx
apps/web/vibes/soul/primitives.ts
apps/web/vibes/soul/primitives/compare-card/index.tsx

- adds content for `product.description` & `product.customfields` to `CompareCard` examples
- adds `prose` to `CompareCard` description
- adds `Reveal` component to descriptions & custom fields
- updates `CompareCard` changelog
https://github.com/user-attachments/assets/1d8220bd-64b7-4c52-ba40-b1367b884986

feat: add Reveal component to CompareCard

---

apps/web/vibes/soul/docs/compare-card.mdx
apps/web/vibes/soul/primitives/compare-card/index.tsx

- adds styling to remove margin-top being added to first element when content is wrapped in div
- updates `CompareCard` docs

feat: remove default margin added by prose

---

apps/web/vibes/soul/primitives/compare-card/index.tsx

- adds React `Fragment` with `key` to fix React `key` error

feat: add Fragment with key to CompareCard

---

apps/web/vibes/soul/docs/button.mdx
apps/web/vibes/soul/primitives/button/index.tsx

- removes `loading` prop from disabled state
- adds correct `disabled` Tailwind classes
https://github.com/user-attachments/assets/416e4906-502d-4650-b108-0951785a706d

fix: button loading and disabled styles

---

apps/web/vibes/soul/docs/card-radio-group.mdx

- fixes `CardRadioGroup` props in docs

fix: card-radio-group props in docs

---

apps/web/vibes/soul/docs/checkbox.mdx
apps/web/vibes/soul/form/checkbox/index.tsx

Adds Tailwind classes used to style the checkbox input and label based on the disabled state of the checkbox. 
Default:
https://github.com/user-attachments/assets/e4fdfed8-930b-4ea5-8038-1ea71c63f6e5
Disabled:
https://github.com/user-attachments/assets/1a044ff6-1923-478e-ae36-07ca858afdf3
Checked + disabled:
https://github.com/user-attachments/assets/c17e4e3b-cecb-494b-b0eb-66ef47748159

feat: add disabled styles for checkbox

---

apps/cli/package.json

chore: publish cli 1.0.0 to npm

---

apps/web/app/(marketing)/docs/[vibe]/[page]/page.tsx
apps/web/vibes/soul/docs/changelog.mdx
apps/web/vibes/soul/examples/form/file-input/index.tsx
apps/web/vibes/soul/registry/form.ts

- adds installation to `FileInput` docs and adds component to registry
https://github.com/user-attachments/assets/42c49e22-cd19-4bfc-adc4-1c163b1ec006

docs: add file-input installation instructions
